### PR TITLE
Fix configuration of TodoCommentChecker

### PR DESCRIPTION
**Pull request by jqno**
I noticed that the given configuration for the TodoCommentChecker doesn't behave as expected. I fixed it in my project; this pull request reflects the changes I made to make it work.

### CODE REVIEW

**Comment by matthewfarwell** [comment]
Thanks!

**Comment by jqno** [comment]
No problem!
I notice that, since I opened this PR, two new versions have come out, which this PR obviously doesn't cover :).
( http://www.scalastyle.org/rules-0.9.0.html and http://www.scalastyle.org/rules-1.0.0.html )

**Comment by matthewfarwell** [comment]
I'll fix these as well when I have a minute.

**Comment by jqno** [comment]
Thanks!

**Pull request merged**
